drop table if exists TIME_ZONE;
drop table if exists DST_RULE;
CREATE TABLE TIME_ZONE
(
    ID int NOT NULL,
    CODE VARCHAR(255) NOT NULL ,
    NAME VARCHAR(255)
);
ALTER TABLE TIME_ZONE
    ADD PRIMARY KEY (Id);

CREATE TABLE DST_RULE
(
    ID int NOT NULL,
    NAME VARCHAR(255)
);
ALTER TABLE DST_RULE
    ADD PRIMARY KEY (Id);